-- opt-in plugins (v0.12.x)
vim.cmd.packadd('nvim.difftool')
vim.cmd.packadd('nvim.tohtml')
vim.cmd.packadd('nvim.undotree')
vim.keymap.set('n', '<leader>u', function() vim.cmd.Undotree() end, { desc = 'Undotree', silent = true })

-- Custom plugins
require('plugins.icon')
require('plugins.mason')
require('plugins.treesitter')
require('plugins.lsp')
-- require('plugins.formatter')
-- require('plugins.colorscheme')
-- require('plugins.transparent')
require('plugins.colorizer')
require('plugins.friendly-snippets')
require('plugins.completion')
require('plugins.comment')
require('plugins.autopairs')
require('plugins.leap')
require('plugins.git')
require('plugins.picker')
require('plugins.quicker')
require('plugins.oil')
require('plugins.cloak')
require('plugins.vimwiki')
require('plugins.csvview')
require('plugins.which-key')
require('plugins.statusline')
require('plugins.tmux-navigator')
-- require('plugins.trouble')
-- require('plugins.kulala')
-- require('plugins.vim-dispatch')
-- require('plugins.markview')
-- require('plugins.yazi')
-- require('plugins.lualine')
-- require('plugins.ctags')
