-- opt-in plugins (v0.12.x)
vim.cmd.packadd('nvim.undotree')

-- Custom plugins
require('plugins.plenary')
require('plugins.icon')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.colorscheme')
require('plugins.colorizer')
require('plugins.friendly-snippet')
require('plugins.completion')
require('plugins.autopairs')
require('plugins.git')
require('plugins.picker')
require('plugins.yazi')
require('plugins.trouble')
require('plugins.tmux')
require('plugins.lualine')
